SubnetTracker/urls.py
"""
    Copyright (C) 2014-2015  Justin Crawford <Justasic@gmail.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^cidradd/', 'SubnetTracker.apps.front.views.cidradd', name='cidradd'),
	url(r'^cidrremove/(\d+)/', 'SubnetTracker.apps.front.views.cidrremove', name='cidrremove'),
	url(r'^cidrlist/', 'SubnetTracker.apps.front.views.cidrlist', name='cidrlist'),
	url(r'^$', 'SubnetTracker.apps.front.views.index'),
)

SubnetTracker/apps/front/models.py
"""
    Copyright (C) 2014-2015  Justin Crawford <Justasic@gmail.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
__author__ = 'justasic'

from django.db import models
from ipaddress import IPv4Network


class CIDR(models.Model):
	""" Basic CIDR model to keep track of all the CIDRs
		It's function is really to just manage the name=cidr
		association and store it in the database.

		The class also uses the 'ipaddress' library to compare
		CIDR masks to itself.
	"""
	name = models.CharField(max_length=255)
	cidr = models.CharField(max_length=20)

	def __unicode__(self):
		return unicode(self.name)

	def CIDROverlaps(self, addr):
		""" This function checks if the CIDR networks or addresses overlap.

			addr - takes a string (preferably Unicode) of the CIDR network mask or
					an ipaddress.IPv4Network object.
		"""
		if isinstance(addr, IPv4Network):
			return addr.overlaps(IPv4Network(unicode(self.cidr)))
		else:
			return IPv4Network(unicode(addr)).overlaps(IPv4Network(unicode(self.cidr)))

SubnetTracker/apps/front/views.py
"""
    Copyright (C) 2014-2015  Justin Crawford <Justasic@gmail.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
__author__ = 'justasic'

# Django imports
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.forms import ModelForm
from django.http import HttpResponse, HttpResponseBadRequest
from ipaddress import IPv4Network, AddressValueError
import json

# Import our CIDR model
from SubnetTracker.apps.front.models import CIDR


class CIDRForm(ModelForm):
	""" This is an extension of the CIDR Model to make
		a nice Django Form out of it. This makes
		using the form and saving its data really
		easy.
	"""
	class Meta:
		model = CIDR


class AddressExists(Exception):
	""" This is really just to take advantage of the already
		needed try statement in the 'cidradd' function below.
		It makes it easy to return a response while including
		the CIDR object for reference.
	"""
	def __init__(self, message, cidr):
		Exception.__init__(self, message)
		self.cidr = cidr


def index(request):
	""" Renders and returns the index HTML page
		which lists all known CIDR masks and their names
		as well as a form to submit and check new CIDR masks
	"""
	ctx = RequestContext(request, {
			'cidrs': CIDR.objects.all(),
			'cidr_form': CIDRForm(),
		})

	return render_to_response('front/index.html', ctx)


def cidradd(request):
	""" Checks that the CIDR submitted is valid.
		If the CIDR is valid, it adds it to the database, updates the list, and updates
		any AJAX clients.

		If the CIDR is invalid, it returns and error and updates nothing.
	"""
	jsonresponse = {}
	# Make sure it's a post request or that the request is AJAX, otherwise give
	# a bad request error
	if request.is_ajax() or request.method == 'POST':
		form = CIDRForm(data=request.POST)
		if form.is_valid():
			# get the model without saving to the database.
			model = form.save(commit=False)
			try:
				# Check and make sure the CIDR mask is valid
				ip = IPv4Network(unicode(model.cidr))
				# Check that the CIDR mask doesn't already overlap an existing CIDR mask.
				for c in CIDR.objects.all():
					if c.CIDROverlaps(ip):
						raise AddressExists(u"CIDR address already exists", c)

				# Commit the form to the database.
				model = form.save()
				jsonresponse = {'success': model.id}
				del ip
			except (AddressValueError, ValueError):
				# Check that the CIDR mask is valid.
				jsonresponse = {'error': 'Invalid CIDR mask'}
			except AddressExists as e:
				# Check that the CIDR mask doesn't exist already.
				jsonresponse = {'error': e.message, 'id': e.cidr.id, 'name': e.cidr.name}
			except:
				# Some other error that requires debugging. Return a generic error.
				jsonresponse = {'error': 'Server error'}
				raise
		else:
			jsonresponse = {'error': 'Please fill out all form fields'}
	else:
		# this really should return a 400 error.
		jsonresponse = {'error': 'Request must be ajax or POST'}

	# Return our response.
	return HttpResponse(json.dumps(jsonresponse), content_type='application/json')


def cidrremove(request, row_id):
	""" This function is the AJAX function which
		removes a CIDR address from the database
		as long as it exists.

		If the requested data does not exist, send a bad request.
	"""
	obj = CIDR.objects.filter(id=row_id)
	if obj:
		obj.delete()
	else:
		return HttpResponseBadRequest

	return HttpResponse(json.dumps({'success': u"Successfully deleted item %s" % row_id}), \
						content_type='application/json')


def cidrlist(request):
	""" This function returns a JSON encoded list of all the
		CIDR addresses, names, and database ids.
		This will be called every 2 or 5 seconds as an AJAX
		call to check for any change in the list of known
		CIDR addresses.
	"""
	cidrobjects = []

	for c in CIDR.objects.all():
		cidrobjects.append({'name': c.name, 'mask': c.cidr, 'id': c.id})
	return HttpResponse(json.dumps(cidrobjects), content_type='application/json')

SubnetTracker/templates/base.html
{% comment %}
    Copyright (C) 2014-2015  Justin Crawford <Justasic@gmail.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{# The point of this document is to have all pages inherit from it. #}
{# This inheritance makes all pages equal in how their HTML is formatted. #}
{# there are basic 'head' and 'body' blocks for most of the content as well #}
{# as 'scripts' and 'title' blocks. #}
{# This file has been in every django project I ever worked on and it doesn't change much. #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

SubnetTracker/templates/front/index.html
{% comment %}
    Copyright (C) 2014-2015  Justin Crawford <Justasic@gmail.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{# Extend the basic HTML template. #}
{% extends 'base.html' %}
{% load staticfiles %}

{# Set window title #}
{% block title %}Subnets{% endblock %}

{# Include any CSS or JS assets into the page. #}
{% block head %}
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/front.css' %}">
{% endblock %}

{# Define the page content. #}
{% block body %}
    <h1 class="title">Current CIDR subnets</h1>
    <div class="table">
    {# A simple table. I could have done a bunch of div/span stuff but I find tables #}
    {# much easier to use than doing a bunch of CSS stuff and div/spans. #}
    <table class="subnet_table">
        <thead>
            <tr>
                <th>Name</th>
                <th>CIDR</th>
            </tr>
        </thead>

        {% for c in cidrs %}
            <tr id="cidr_{{ c.id }}">
                <td>{{ c.name }}</td>
                <td>{{ c.cidr }}</td>
		{# I'll admit. I cheated here a bit but I really didn't feel like finding #}
		{# the id of the row to remove so I just used this. It seems a bit more efficient #}
		{# in my mind too compared to having to iterate all over the page for one thing. #}
                <td id="x_button"><a href="javascript:deleteRow({{ c.id }})">Remove '{{ c.name }}'</a></td>
            </tr>
        {% endfor %}
    </table>
    </div>

    <br />
    <div class="form">
        <p>Add a CIDR address: <div class="error"></div></p>
        <form action="/cidradd/" method="POST" id="form">{% csrf_token %}
            Name: {{ cidr_form.name }}
            CIDR: {{ cidr_form.cidr }}
            <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

{# This block is put at the bottom of the page <body> tag in the HTML page. #}
{# Used for scripts and other misc. page items. #}
{% block scripts %}
    <script type="text/javascript">
    /* Handle the AJAX call to add a CIDR mask */
    var frm = $('#form');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            dataType: 'json',
            success: function (res) {
                if(res.error){
                    var e = $(".error");
                    if(res.id){
                        e.text("CIDR address already allocated as '" + res.name + "'");
                    }else{
                        e.text(res.error);
                    }
                    e.show();
                }else{
                    $(".error").hide();
                    var name = $('#id_name');
                    var cidr = $('#id_cidr');
                    addRow(res.success, name.val(), cidr.val());
                    handleUpdate(true);
                    name.val('');
                    cidr.val('');
                }
            },
            error: function(data) {
                var e = $(".error");
                e.text("A server error occured.");
                e.show();
            }
        });
        return false;
    });

    /* Handle the deletion of an item */
    function deleteRow(row_id){
        $.get("/cidrremove/"+row_id+"/").done(function(){
            removeRow(row_id);
        }).fail(function(){
            alert("Server error occured.");
        });}

    /* These are helper functions for handleUpdate to make the code cleaner */
    function removeRow(row_id){
        $('#cidr_'+row_id).remove();
    }

    function addRow(row_id, name, cidr){
        $(".subnet_table tr:last").after('<tr id="cidr_'+row_id+'"><td>'+name+'</td><td>'+cidr+
            '</td><td><a href="javascript:deleteRow('+row_id+')">Remove \''+name+'\'</a></td></tr>');
    }

    /*  This function is used to check if an item is in an array.
	Normally I would use $.InArray() from JQuery but it does
	comparison on objects, not sub-items of those objects.
	Here I checked if the item name is somewhere in the
	array of objects */
    function inArray(item, array){
        for(var i = 0; i < array.length; i++)
        {
            if(item.name === array[i].name)
                return true;
        }
        return false;
    }

    /* Handle live updating of the table */
    var tableData;
    function handleUpdate(forceUpdate){
	/* Run an AJAX call to the server and grab a JSON list of all the
	   current CIDR masks. We will either compare it to an existing list
	   (eg. tableData) or we will update the tableData list dependinng on
	   whether 'forceUpdate' is set to true or not. */
        $.ajax({
           url: '/cidrlist/',
           dataType: 'json',
           success: function(_data){
               var data = [];
               $.each(_data, function(i, item){data[i] = item;});
               /* force an update and disregard array comparisons. */
               if(forceUpdate){
			tableData = data;
               }else{
                   /* Compare the existing array to check if an item was removed server-side */
                   for(var i = 0; i < tableData.length; i++){
                       if(!inArray(tableData[i], data)){removeRow(tableData[i].id);}}

                   /* Compare the existing array to check if an item was added server-side */
                   for(var i = 0; i < data.length; i++){
                       if (!inArray(data[i], tableData)){addRow(data[i].id, data[i].name, data[i].mask);}}

		   /* Update the tableData variable. This prevents repeatedly adding data to the table */
                   tableData = data;
               }
           }
        });
    }
    /* Check for updates every 2 seconds - I hate to use timers but it seems I have to. */
    $(document).ready(function(){ handleUpdate(true); setInterval(function(){handleUpdate(false)}, 2000); });
    </script>
{% endblock %}